name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-dockerhub-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "9921248683" | docker login -u "rushikeshmule9921" --password-stdin

      - name: Build, Tag, and Push Image to Docker Hub
        env:
          DOCKER_REPO: rushikeshmule9921/my-cricket-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the Docker image
          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          
          # Push the image to Docker Hub
          docker push $DOCKER_REPO:$IMAGE_TAG
          echo "::set-output name=image::$DOCKER_REPO:$IMAGE_TAG"