name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-dockerhub-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "rushikeshmule9921" --password-stdin

      - name: Build, Tag, and Push Image to Docker Hub
        env:
          DOCKER_REPO: rushikeshmule9921/my-cricket-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the Docker image
          docker build -t $DOCKER_REPO:$IMAGE_TAG .
          
          # Push the image to Docker Hub
          docker push $DOCKER_REPO:$IMAGE_TAG
          echo "::set-output name=image::$DOCKER_REPO:$IMAGE_TAG"

  Continuous-Deployment:
    needs: build-and-push-dockerhub-image
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "rushikeshmule9921" --password-stdin

      - name: Pull Latest Image from Docker Hub
        env:
          DOCKER_REPO: rushikeshmule9921/my-cricket-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $DOCKER_REPO:$IMAGE_TAG

      - name: Run Docker Image
        env:
          DOCKER_REPO: rushikeshmule9921/my-cricket-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker run -d -p 8080:8080 --ipc="host" --name=csp_app \
            -e 'AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}' \
            -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
            -e 'AWS_REGION=${{ secrets.AWS_REGION }}' \
            $DOCKER_REPO:$IMAGE_TAG

      - name: Clean Previous Images and Containers
        run: |
          docker system prune -f
